import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConditionalHeader from "@/components/ConditionalHeader";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import Starfield from "@/components/Starfield";
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <SessionProvider>
            <Starfield />
            <div className="app-shell">
              <ConditionalHeader />
              <Navbar />
              <main className="flex-grow page-center">{children}</main>
              <Footer />       
            </div>
          </SessionProvider>
      </body>
    </html>
  );
}
